# [Info]
site_name: UnicornZhen的个人博客 # 左上角标题
site_url: https://unicornZhen.github.io
site_author: UnicornZhen
site_description: UnicornZhen的个人博客

# [Navigtion]
nav:
  - 算法:
    - ALGORITHM/index.md 
    - DaiMaSuiXiangLu:
      - day1 数组part01: ALGORITHM/DaiMaSuiXiangLu/day1_Array_part01.md
      - day2 数组part02: ALGORITHM/DaiMaSuiXiangLu/day2_Array_part02.md
      - day3 链表part01: ALGORITHM/DaiMaSuiXiangLu/day3_LinkedList_part01.md
      - day4 链表part02: ALGORITHM/DaiMaSuiXiangLu/day4_LinkedList_part02.md
      - day6 哈希表part01: ALGORITHM/DaiMaSuiXiangLu/day6_HashTable_part01.md
      - day7 哈希表part02: ALGORITHM/DaiMaSuiXiangLu/day7_HashTable_part02.md
      - day8 字符串part01: ALGORITHM/DaiMaSuiXiangLu/day8_String_part01.md
      - day9 字符串part02: ALGORITHM/DaiMaSuiXiangLu/day9_String_part02.md
      - day10 栈和队列part01: ALGORITHM/DaiMaSuiXiangLu/day10_StackAndQueue_part01.md
  - 项目学习:
    - PROJECTS/index.md
    - BUSTUB:
      - p1 buffer pool: PROJECTS/BUSTUB/Bustub_1.md
  - 我:
    - ME/index.md



# [UI]
## [top]
theme:
  name: material
  palette:
    - scheme: default # 日间模式
      primary: indigo # 上方的
      accent: orange # 链接等可交互元件的高亮色
      toggle:
        icon: material/weather-night # 图标
        name: 切换至夜间模式 # 鼠标悬浮提示
    - scheme: slate # 夜间模式
      primary: indigo
      accent: orange
      toggle:
        icon: material/weather-sunny
        name: 切换至日间模式
  features:
    - navigation.tabs # 使用Tab来进行分类
    - navigation.top # 返回顶部的按钮 在上滑时出现
    - navigation.indexes # Tab会有一个index.md 而不是在打开Tab时打开第一篇文章
    - navigation.expand # 打开Tab时左侧目录全部展开
    - search.suggest # 搜索输入一些字母时推荐补全整个单词
    - search.highlight # 搜索出的文章关键词加入高亮
    - content.code.copy # 可以通过按钮复制代码
    - content.action.edit # 点击按钮跳转到编辑页面  需要结合 edit_uri 一起使用
  language: zh # 一些提示性的文字会变成中文
  icon:
    repo: fontawesome/brands/github
edit_uri: edit/main/docs # 编辑按钮跳转的链接
## [top-right corner]
repo_url: https://github.com/unicornZhen/unicornZhen.github.io # 右上角点击跳转的链接
repo_name: UnicornZhen.github.io # 右上角的名字
## [bottom-left corner]
copyright: UnicornZhen CC-BY-4.0 # 左下角的版权声明
## [bottom-right corner]
extra:
  social: # icons
    - icon: fontawesome/brands/bilibili
      link: https://space.bilibili.com/3546606391528011
      name: Bilibili | music_二次元 # 鼠标悬浮提示
    - icon: fontawesome/brands/github
      link: https://github.com/unicornZhen
      name: GitHub | UnicornZhen

# [Extensions]
plugins:
  - search: # 现在还不支持中文搜索 支持之后可以设置语言
    # insider已经支持中文的分词搜索了 https://squidfunk.github.io/mkdocs-material/blog/2022/chinese-search-support/
      lang:
        - en
        - ja
  - tags # 给单篇文章添加标签 https://squidfunk.github.io/mkdocs-material/setup/setting-up-tags/?h=tags
markdown_extensions:
  - pymdownx.arithmatex: # 数学公式支持
      generic: true
  - attr_list # 给图片后面添加{width="300"}设置大小
  - toc:
      permalink: true # 固定标题位置为当前位置
  - pymdownx.highlight: # 代码块高亮
      # linenums: true # 显示行号
      # auto_title: true # 显示编程语言名称
  - pymdownx.superfences # 代码块高亮插件
  - meta # 支持Markdown文件上方自定义标题标签等
  - admonition # https://squidfunk.github.io/mkdocs-material/reference/admonitions/#inline-blocks
  - pymdownx.details # admonition需要

extra_javascript:
  # 数学公式支持
  # https://squidfunk.github.io/mkdocs-material/reference/math/#katex
  - mkdocs/javascripts/katex.js
  - https://cdnjs.cloudflare.com/ajax/libs/KaTeX/0.16.7/katex.min.js  
  - https://cdnjs.cloudflare.com/ajax/libs/KaTeX/0.16.7/contrib/auto-render.min.js
extra_css:
  - https://cdnjs.cloudflare.com/ajax/libs/KaTeX/0.16.7/katex.min.css
  - mkdocs/css/no-footer.css # 不使用底部的翻页
  - mkdocs/css/unordered-list-symbols.css # multiplt unordered list symbols
